"""Initial Migration Development

Revision ID: f44b9eb65595
Revises: 
Create Date: 2021-02-15 15:04:10.105790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f44b9eb65595'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_name', sa.String(length=80), nullable=False),
    sa.Column('student_roll', sa.Integer(), nullable=False),
    sa.Column('student_class', sa.String(length=80), nullable=False),
    sa.Column('student_phone', sa.Integer(), nullable=True),
    sa.Column('student_email', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_name', sa.String(length=80), nullable=False),
    sa.Column('author_name', sa.String(length=80), nullable=False),
    sa.Column('isbn_number', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    op.drop_table('students')
    # ### end Alembic commands ###
