"""location attribute added to Puppy Class

Revision ID: 0a9825fb7736
Revises: 3b1186f367aa
Create Date: 2021-01-16 17:44:43.358440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a9825fb7736'
down_revision = '3b1186f367aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puppies', sa.Column('location', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('puppies', 'location')
    # ### end Alembic commands ###
